import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';

import 'core/services/mood_provider.dart';
import 'core/services/counsellor_provider.dart';
import 'core/services/audio_service.dart';
import 'core/theme/app_theme.dart';

import 'features/splash/splash_screen.dart';
import 'features/splash/onboarding_screen.dart';
import 'features/splash/welcome_screen.dart';
import 'features/home/home_screen.dart';
import 'features/auth/login_screen.dart';
import 'features/auth/register_screen.dart';
import 'features/chat/user_chat_screen.dart';
import 'features/counsellor/counsellor_login_screen.dart';
import 'features/counsellor/counsellor_dashboard.dart';
import 'features/call/call_booking_screen.dart';

// TODO: Replace with your own firebase_options.dart generated by
// `flutterfire configure`
// import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  // Replace DefaultFirebaseOptions.currentPlatform with your own options
  try {
    await Firebase.initializeApp(
      // options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    // In POC mode without Firebase configured, we continue without it
    debugPrint('Firebase init skipped: $e');
  }

  // Pre-load all mood audio files so switching is instant
  AudioService().preloadAll();

  runApp(const MindALotApp());
}

class MindALotApp extends StatelessWidget {
  const MindALotApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => MoodProvider()),
        ChangeNotifierProvider(create: (_) => CounsellorProvider()),
      ],
      child: Consumer<MoodProvider>(
        builder: (context, moodProvider, _) {
          return MaterialApp(
            title: 'MindALot',
            debugShowCheckedModeBanner: false,
            // Theme adapts to current mood
            theme: AppTheme.moodTheme(moodProvider.currentMood),
            initialRoute: '/',
            routes: {
              '/': (_) => const SplashScreen(),
              '/onboarding': (_) => const OnboardingScreen(),
              '/welcome': (_) => const WelcomeScreen(),
              '/login': (_) => const LoginScreen(),
              '/register': (_) => const RegisterScreen(),
              '/home': (_) => const HomeScreen(),
              '/chat': (_) => const UserChatScreen(),
              '/counsellor-login': (_) => const CounsellorLoginScreen(),
              '/counsellor-dashboard': (_) => const CounsellorDashboard(),
              '/call-booking': (_) => const CallBookingScreen(),
            },
          );
        },
      ),
    );
  }
}
